version: "3.4"

networks:
  opba-net:

x-sandbox-hosts: &sandbox-hosts
  COMMON_APPS_LOCAL_ASPSPPROFILE_HOST: x2sa-sandbox-aspspprofile
  COMMON_APPS_LOCAL_ASPSPPROFILE_PORT: 8080
  COMMON_APPS_LOCAL_CERTGENERATOR_HOST: x2sa-sandbox-certgenerator
  COMMON_APPS_LOCAL_CERTGENERATOR_PORT: 8092
  COMMON_APPS_LOCAL_CONSENTMGMT_HOST: x2sa-sandbox-consentmgmt
  COMMON_APPS_LOCAL_CONSENTMGMT_PORT: 8080
  COMMON_APPS_LOCAL_LEDGERSAPP_HOST: x2sa-sandbox-ledgersapp
  COMMON_APPS_LOCAL_LEDGERSAPP_PORT: 8088
  COMMON_APPS_LOCAL_LEDGERSGATEWAY_HOST: x2sa-sandbox-ledgersgateway
  COMMON_APPS_LOCAL_LEDGERSGATEWAY_PORT: 8089
  COMMON_APPS_LOCAL_ONLINEBANKING_HOST: x2sa-sandbox-onlinebanking
  COMMON_APPS_LOCAL_ONLINEBANKING_PORT: 8090
  COMMON_APPS_LOCAL_TPPREST_HOST: x2sa-sandbox-tpprest
  COMMON_APPS_LOCAL_TPPREST_PORT: 8093
  COMMON_APPS_LOCAL_TPP_UI_HOST: x2sa-sandbox-tpp-ui
  COMMON_APPS_LOCAL_TPP_UI_PORT: 4205
  COMMON_APPS_LOCAL_ONLINEBANKINGUI_HOST: x2sa-sandbox-onlinebankingui
  COMMON_APPS_LOCAL_ONLINEBANKINGUI_PORT: 4400 # this port seem to be used in lot of places, hard to change

services:
  #
  #
  #          ========================= SANDBOX ==================================
  #
  #
  xs2a-sandbox-postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=sandbox_apps
    ports:
      #HOST:CONTAINER
      - 25432:5432
    volumes:
      - ./opba-protocols/sandboxes/xs2a-sandbox/src/main/resources/sandbox/prepare-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - opba-net

  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=open_banking
    ports:
      #HOST:CONTAINER
      - "15432:5432"
    volumes:
      - ./opba-db/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./fintech-examples/fintech-db-schema/src/main/resources/init.sql:/docker-entrypoint-initdb.d/fintech-init.sql
    networks:
      - opba-net

  open-banking-gateway:
    environment:
      - SPRING_LIQUIBASE_PARAMETERS_ADORSYS-SANDBOX-URL=http://x2sa-sandbox-ledgersgateway:8089
      - SPRING_LIQUIBASE_PARAMETERS_ADORSYS-HBCI-SANDBOX-URL=http://hbci-sandbox:8090/hbci-mock/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/open_banking?currentSchema=banking_protocol
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=docker
      - PROTOCOL_XS2A_PKCS12_KEYSTORE=/pkcs12/sample-qwac.keystore
      - FACADE_ENCRYPTION_KEYSETPATH=/keysetpath/example-keyset.json
      - FACADE_URLS_EMBEDDED-UI-BASE-URL=http://localhost:14200
      - PROTOCOL_GATEWAY-BASE-URL=http://localhost:18085
      - SPRING_PROFILES_ACTIVE=no-signature-filter
      - BPMNSHARED_FLOWABLE_SERIALIZATION_MAX_LENGTH=1
    image: adorsys/open-banking-gateway-open-banking-gateway:0.19.1
    ports:
      - "18085:8085"
    volumes:
      - ./opba-protocols/xs2a-protocol/src/main/resources/:/pkcs12/
      - ./opba-banking-protocol-facade/src/main/resources/:/keysetpath/
    depends_on:
      - postgres
    networks:
      - opba-net

  x2sa-sandbox-onlinebankingui:
    image: adorsys/xs2a-online-banking-ui:3.7.1
    environment:
      ONLINE_BANKING_SERVER_URL: http://x2sa-sandbox-onlinebanking:8090
    ports:
      - 4400:4400
    depends_on:
      - x2sa-sandbox-onlinebanking
    networks:
      - opba-net

  x2sa-sandbox-tpprest:
    image: adorsys/xs2a-tpp-rest-server:3.7.1
    environment:
      <<: *sandbox-hosts
      SPRING_PROFILES_INCLUDE: test-db-local-postgres,test-common,test-tpp-rest
      SPRING_CONFIG_LOCATION: classpath:/,/configs/application-test-common.yml,/configs/application-test-db-local-postgres.yml,/configs/application-test-tpp-rest.yml
      DB_HOST_AND_PORT: xs2a-sandbox-postgres:5432
    ports:
      - 20016:8093
    depends_on:
      - x2sa-sandbox-onlinebankingui
      - x2sa-sandbox-ledgersapp
    volumes:
      - ./opba-protocols/sandboxes/xs2a-sandbox/src/main/resources/sandbox:/configs
    networks:
      - opba-net

  x2sa-sandbox-tpp-ui:
    image: adorsys/xs2a-bank-tpp-ui:3.7.1
    environment:
      <<: *sandbox-hosts
      TPP_REST_SERVER_URL: http://x2sa-sandbox-tpprest:8093
      CERT_GEN_URL: http://x2sa-sandbox-certgenerator:8092
      CERT_GEN_ENABLED: "true"
    ports:
      - 4205:4205
    networks:
      - opba-net
    depends_on:
      - x2sa-sandbox-certgenerator
      - x2sa-sandbox-tpprest

  x2sa-sandbox-onlinebanking:
    image: adorsys/xs2a-online-banking:3.7.1
    environment:
      <<: *sandbox-hosts
      SPRING_PROFILES_INCLUDE: test-db-local-postgres,test-common,test-online-banking
      SPRING_CONFIG_LOCATION: classpath:/,/configs/application-test-common.yml,/configs/application-test-db-local-postgres.yml,/configs/application-test-online-banking.yml
      DB_HOST_AND_PORT: xs2a-sandbox-postgres:5432
    ports:
      - 20015:8090
    depends_on:
      - xs2a-sandbox-postgres
      - x2sa-sandbox-ledgersapp
      - x2sa-sandbox-ledgersgateway
    volumes:
      - ./opba-protocols/sandboxes/xs2a-sandbox/src/main/resources/sandbox:/configs
    networks:
      - opba-net

  x2sa-sandbox-ledgersgateway:
    image: adorsys/xs2a-connector-examples:7.4.1
    environment:
      <<: *sandbox-hosts
      SPRING_PROFILES_INCLUDE: test-db-local-postgres,test-common,test-ledgeres-gateway,postgres,mock-qwac,remote
      SPRING_CONFIG_LOCATION: classpath:/,/configs/application-test-common.yml,/configs/application-test-db-local-postgres.yml,/configs/application-test-ledgers-gateway.yml
      DB_HOST_AND_PORT: xs2a-sandbox-postgres:5432
    ports:
      - 20014:8089
    depends_on:
      - x2sa-sandbox-ledgersapp
      - x2sa-sandbox-aspspprofile
      - x2sa-sandbox-consentmgmt
    volumes:
      - ./opba-protocols/sandboxes/xs2a-sandbox/src/main/resources/sandbox:/configs
    networks:
      - opba-net

  x2sa-sandbox-ledgersapp:
    image: adorsys/ledgers:3.4
    environment:
      <<: *sandbox-hosts
      SPRING_PROFILES_INCLUDE: test-db-local-postgres,test-common,test-ledgeres-app,develop,sandbox
      SPRING_CONFIG_LOCATION: classpath:/,/configs/application-test-common.yml,/configs/application-test-db-local-postgres.yml,/configs/application-test-ledgers-app.yml
      DB_HOST_AND_PORT: xs2a-sandbox-postgres:5432
    ports:
      - 20013:8088
    depends_on:
      - xs2a-sandbox-postgres
    volumes:
      - ./opba-protocols/sandboxes/xs2a-sandbox/src/main/resources/sandbox:/configs
    networks:
      - opba-net

  x2sa-sandbox-consentmgmt:
    image: adorsys/xs2a-consent-management:7.4
    environment:
      <<: *sandbox-hosts
      SPRING_PROFILES_INCLUDE: test-db-local-postgres,test-common,test-consent-mgmt
      SPRING_CONFIG_LOCATION: classpath:/,/configs/application-test-common.yml,/configs/application-test-db-local-postgres.yml,/configs/application-test-consent-mgmt.yml
      DB_HOST_AND_PORT: xs2a-sandbox-postgres:5432
    ports:
      - 20012:8080
    depends_on:
      - xs2a-sandbox-postgres
    volumes:
      - ./opba-protocols/sandboxes/xs2a-sandbox/src/main/resources/sandbox:/configs
    networks:
      - opba-net

  x2sa-sandbox-certgenerator:
    image: adorsys/xs2a-certificate-generator:3.7.1
    environment:
      <<: *sandbox-hosts
      SPRING_PROFILES_INCLUDE: test-db-local-postgres,test-common,test-cert-generator
      SPRING_CONFIG_LOCATION: classpath:/,/configs/application-test-common.yml,/configs/application-test-db-local-postgres.yml,/configs/application-test-cert-generator.yml
      DB_HOST_AND_PORT: xs2a-sandbox-postgres:5432
    ports:
      - 20011:8092
    depends_on:
      - xs2a-sandbox-postgres
    volumes:
      - ./opba-protocols/sandboxes/xs2a-sandbox/src/main/resources/sandbox:/configs
    networks:
      - opba-net

  x2sa-sandbox-aspspprofile:
    image: adorsys/xs2a-aspsp-profile:7.4
    environment:
      <<: *sandbox-hosts
      PRIMARY_PROFILE: /configs/application-test-aspsp-profile.yml
      SPRING_PROFILES_INCLUDE: test-db-local-postgres,test-common,test-aspsp-profile,debug_mode
      SPRING_CONFIG_LOCATION: classpath:/,/configs/application-test-common.yml,/configs/application-test-db-local-postgres.yml,/configs/application-test-aspsp-profile.yml
      DB_HOST_AND_PORT: xs2a-sandbox-postgres:5432
    ports:
      - 20010:8080
    depends_on:
      - xs2a-sandbox-postgres
    volumes:
      - ./opba-protocols/sandboxes/xs2a-sandbox/src/main/resources/sandbox:/configs
    networks:
      - opba-net

  fintech-ui:
    environment:
      - BACKEND_URL=http://fintech-server:8086
    restart: on-failure
    image: "adorsys/open-banking-gateway-fintech-ui:0.19.1"
    ports:
      - "24200:4200"
    depends_on:
      - fintech-server
    networks:
      - opba-net

  fintech-server:
    environment:
      - TPP_URL=http://open-banking-gateway:8085
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/open_banking?currentSchema=fintech

      - FINTECH-UI_HOST=http://localhost:24200

    image: "adorsys/open-banking-gateway-fintech-server:0.19.1"
    ports:
      - "18086:8086"
    depends_on:
      - postgres
    networks:
      - opba-net


  consent-ui:
    environment:
      - BACKEND_URL=http://open-banking-gateway:8085
    restart: on-failure
    image: "adorsys/open-banking-gateway-consent-ui:0.19.1"
    ports:
      - "14200:4200"
    depends_on:
      - open-banking-gateway
    networks:
      - opba-net
