server:
  port: 8086
  controller:
    cookie:
      secure: false
      maxAge: 300
      httpOnly: false
      path: /
      sameSite: Lax
      # sameSite: Strict|Lax|none

tpp:
  url: http://localhost:8085

mock:
  tppais:
    listtransactions: false
    listaccounts: false

spring:
  datasource:
    url: jdbc:postgresql://localhost/open_banking?currentSchema=fintech
    username: postgres
    password: docker
  liquibase:
    change-log: classpath:master.xml

fintech-ui:
  redirect-url: http://localhost:4444/{redirectUri}/{redirectCode}
  exception-url: http://localhost:4444/excaption-redirect
