server:
  port: 8086
  controller:
    sessioncookie:
      secure: false
      maxAge: 300
      httpOnly: true
      path: /
      sameSite: Strict

    redirectcookie:
      secure: false
      maxAge: 1800
      httpOnly: false
      path: /v1/{auth-id}/fromConsentOk
      sameSite: Strict

      # sameSite: Strict|Lax|none
      # samesite SameSite prevents the browser from sending this cookie along with cross-site requests. Possible values for the flag are lax or strict.
      # The strict value will prevent the cookie from being sent by the browser to the target site in all cross-site browsing context, even when following a regular link.
      # The lax value will only send cookies for TOP LEVEL navigation GET requests. This is sufficient for user tracking, but it will prevent many CSRF attacks.

tpp:
  url: http://localhost:8085
  fintechID: MY-SUPER-FINTECH-ID
  serviceSessionPassword: qwerty

mock:
  tppais:
    listaccounts: false
    listtransactions: false

spring:
  datasource:
    url: jdbc:postgresql://localhost/open_banking?currentSchema=fintech
    username: postgres
    password: docker
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: fintech
  liquibase:
    enabled: true
    change-log: classpath:migration/master.xml
    parameters:
      table-prefix: opb_
  jpa:
    hibernate:
      naming:
        physical-strategy: de.adorsys.opba.fintech.impl.database.hibernate.PrefixAndSnakeCasePhysicalNamingStrategy
      # DDL is handled by Liquibase
      ddl-auto: validate

fintech-ui:
  redirect-url: http://localhost:4444/redirect-after-consent?redirectCode={redirectCode}
  unauthorized-url: http://localhost:4444/
  exception-url: http://localhost:4444/excaption-redirect

security:
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCaf3/SSpJipSZhyiEKXOQExcsaghcHko8VG3E7YkhulCmVZuTstg0A7/VVWR77hSOHLJ8ebaVQUXz8nEliVNtV64z6ncaJt2Wc7MflfE8P4j8rm3cxdD7oufGrzVBg62FT1uitMgZCyRLTwkxPQO2PNnC3RUkUg5jZ1qtoAok+TRWcT1FhB1K3CLj5JmaFiFCpn9Y+8U8AaJkTwdd+eQlS3upd6aZZqaC4DSlpFPu6IcbVWStUhPt6IHdaaLGR1WAPhtuZFnN55yxDuImUEaTruQ7U9zAPxb+utjDZN8cohkfhbIB/4gVkKm3lJsEI4BB4PRE7QEYg/vbZLdak4B6bAgMBAAECggEAQTfLLGlATBXtEuCxe99kfcNFDmaV9CNg9QcFkIzXiJ5Qw3mQ73+WE6w3wxSA6Kn2KmyiqsScQUB042nR7IlnoWhytaR+l8nsQgcOBwink0vtYKoa8axhlfpQUzazVIZoKm0RAXOZgv3ATdW6QsZkwcy4XhUIWXmHv4VIC/ruFnborwF0JhuS8kcOcRxc3OuIeKbivL4XXCM7Q6/XFL7KRCzUwMJ4IBQJMBAiO8ky+seNHQWqn+Ej8heaHAOflP2fPSLf8NZaLcuvioqHO4StYEyWrlrP0HQ5VbscCSU9/8Q4B0TzTxlVGJTZO9VB/asL/D+Tk+RawsXtfUtZ4crtKQKBgQDf7fj+EhRbhW/LHMFk98/K9fUZkAXCysKVoCfcQgjuTisHxdoR1GXgjhDwOvLvr5m4TrI73AccMNnlvWjihCLC+FpAPVMyszwbmhF4UkFT23SU/CytF+JvlS/4kfde3xGavOoy9dw9Hs2IHIocNobTMtG8/epRUcxNLlwGJCzhtwKBgQCwn+2Z8egxpmCdUPkLf6IY5YpWMbYucOci6hoLLw72Iktw1ZqzCwOmEWn+5ud+HC6vz3YSEu+ZpqX7AXe9IgaiSLUiIU4hZVTIHNTF28tBhIxUgluwdNaqS28Wi/TvFWcFHJ2raok33ExhtdwPZ6xP1MLXeClNQPkyFzCKp8xaPQKBgH9gX3UulZPl2EyiI8QqTnG17ODIku5V5c+01Vet3GSp5EI8oinoNrdAOJReA9ihe4Bii3IPW6AGjbvoPSQ0Y42iNbw65ft+Bt/wiKV3rJ9lwvAIbeVcI7qzEyGC7kJyAxKRCWtJfSjrP6CAE3Ou9IxoaPPnP4VYUS1KBKCdrUYLAoGBAKMFKZ+CSIazAs+Qshzr0+hYzKMbxQP+T0fJfPo/l/aT1r+xV9TTYK3Buux7oMSkLG8288pg0ecmimIvi530rtzQcOasiNmIFoWRHs30PRkexwslOo2WeZ+6ejD8Qrj9LxXnwJs7fKUjXxh8az2IueEBBkkr7isQwjB6eOIxWAsdAoGAYBP2t9YfGUxVzQ949rVnpVWuscfMYgy0SCVZ5+BzeYMBJFHfXY0u9OlKG5i61oqsvdlbKwHgT1EA+iraIt6AxB9ilSoewqEE6vjAVYelhvHWnYVuOEideCR55FSiAIiDekjZNE5S/ggp/9i6gd8Ly+aX5KMHu1td35GNgCuxGZw=
  signIssuer: fintech.com
  signSubject: fintech@awesome-fintech.com