server:
  port: 8086
  controller:
    cookie:
      secure: false
      maxAge: 300
      httpOnly: false
      path: /
      sameSite: none
      # sameSite: Strict|Lax|none

tpp:
  url: http://localhost:8085

mock:
  tppais:
    listtransactions: false
    listaccounts: false

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: SA
    password:
    driver-class-name: org.h2.Driver

fintech-ui:
  # It means URLs have format "http://some-address/more?parameter="
  ok-url: http://localhost:5500/fintech-callback/redirect?fintechRedirectUriOk=
  nok-url: http://localhost:5500/fintech-callback/redirect?fintechRedirectUriNOk=
  exception-url: http://localhost:5500/fintech-callback/excaption-redirect?exception

